### ISSUE TITLE
Make image swarm compatible

### ISSUE THREAD

**Issue by Ineluki** [Tob1asDocker/rpi-nginx#2]
There is currently a bug in swarm that defaults the platform placement to am64 if not set explicitly.
So this image currently doesn't work when using stack deploy.
Inspect output:
```
                "Placement": {
                    "Constraints": [
                        "node.role == manager"
                    ],
                    "Platforms": [
                        {
                            "Architecture": "amd64",
                            "OS": "linux"
                        }
                    ]
                },
```
The same issue has been adressed here in a similar image with a manifest fix: https://github.com/hypriot/rpi-mysql/issues/11
in commit: https://github.com/hypriot/rpi-mysql/pull/12/commits/facccbb79c844356792832af83ff2239f6e08450

Let's hope they fix this soon, but until then this would help a lot (here and for php-fpm). 
Thanks for the great work on these images in any case.

**Comment by Tob1as** [comment]
Hello,

I don't have a Docker Swarm on Raspberry Pi operating myself.

"docker manifest" is not supported when building on Docker Hub. 
I found an [alternative](https://github.com/estesp/manifest-tool) and hope it works the [way I did](https://github.com/Tob1asDocker/rpi-nginx/blob/master/hooks/post_push) it now.

Can you please try this and give me some feedback?

**Comment by Ineluki** [comment]
Works like a charm now on armhf. Good work!

**Comment by Tob1as** [comment]
I had to fix the following [bug](https://github.com/Tob1asDocker/rpi-nginx/issues/3) ... , I hope it still works for you.
