### ISSUE TITLE
manifest for tobi312/rpi-nginx not found

### ISSUE THREAD

**Issue by enricopenzo** [Tob1asDocker/rpi-nginx#3]
Hi, 
thanks for your work on this.
I'm using this image on production on a fleet of raspberry pi 3 with balena and stretch.
I tried to compile today but I've got the following error:

no matching manifest for linux/arm64 in the manifest list entries

See output from "git push banena master" below:

`[Info]     Starting build for selfiebot-ipadpro, user gh_enricopenzo
[Info]     Dashboard link: https://dashboard.balena-cloud.com/apps/1472789/devices
[Info]     Building on arm03
[Info]     Pulling previous images for caching purposes...
[Success]  Successfully pulled cache images
[nginx]    Step 1/9 : FROM tobi312/rpi-nginx
[node]     Step 1/15 : FROM tobi312/rpi-nginx
[nginx]    no matching manifest for linux/arm64 in the manifest list entries
[node]     no matching manifest for linux/arm64 in the manifest list entries
[Error]    Some services failed to build:
[Error]      Service: node
[Error]        Error: no matching manifest for linux/arm64 in the manifest list entries
[Error]      Service: nginx
[Error]        Error: no matching manifest for linux/arm64 in the manifest list entries
[Error]    Not deploying release.
`
Any ideas on how to fix it?

I also posted on https://forums.balena.io/t/problems-with-tobi312-rpi-nginx-image/19271/2
Many thanks

**Comment by Tob1as** [comment]
Hello,

as you already recognized correctly and wrote in the forum, I fixed a related [bug](https://github.com/Tob1asDocker/rpi-nginx/issues/2). I only thought about arm and not about arm64. 
I hope I [fixed](https://github.com/Tob1asDocker/rpi-nginx/commit/f6369bb3c579ef87d00b37cc38462a009eb47aab) both now, please give me feedback.  


![docker_nginx_issues3](https://user-images.githubusercontent.com/292327/61161765-a7ca8e00-a505-11e9-821f-9f38bec6e7cd.PNG)

**Comment by enricopenzo** [comment]
I was able to compile correctly. Thanks for the quick fix!
